# Generated by Django 5.2.4 on 2025-07-27 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JogoLoteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('max_numeros', models.IntegerField()),
                ('numeros_sorteados', models.IntegerField()),
                ('qtd_sorteios', models.IntegerField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('premio_bruto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'Jogo Loteria',
                'verbose_name_plural': 'Jogos Loteria',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Premiacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeros', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fixo', models.BooleanField(default=False)),
                ('percentual', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Premiação',
                'verbose_name_plural': 'Premiações',
                'ordering': ['valor'],
            },
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeros', models.CharField(max_length=100)),
                ('data_jogo', models.DateTimeField(auto_now_add=True)),
                ('premiado', models.BooleanField(default=False)),
                ('valor_premio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('jogo_loteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogos', to='api.jogoloteria')),
            ],
            options={
                'verbose_name': 'Jogo',
                'verbose_name_plural': 'Jogos',
                'ordering': ['-data_jogo'],
            },
        ),
        migrations.AddField(
            model_name='jogoloteria',
            name='premiacoes',
            field=models.ManyToManyField(blank=True, related_name='jogos', to='api.premiacao'),
        ),
    ]
