# Generated by Django 5.2.3 on 2025-07-10 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='premiacao',
            options={'ordering': ['valor'], 'verbose_name': 'Premiação', 'verbose_name_plural': 'Premiações'},
        ),
        migrations.AddField(
            model_name='jogoloteria',
            name='premio_bruto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
